name: lhci-format-action
description: GitHub Actions to format Lighthouse ci results for easy viewing.
inputs:
  json-file-path:
    description: Path of the file generated when lhci is run
    required: true
  report-url: 
    description: url where the report is deployed at lhci runtime
    required: true
outputs:
  status:
    description: Success or Failure.
branding:
  icon: activity
  color: gray-dark
runs:
  using: node16
  main: dist/index.js