name: build with ncc
on: 
  push: 


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: yarn install

      - name: build
        run: yarn build

      - name: add and commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build with ncc
